import numpy as np
from typing import List, Tuple, Optional
from backend.schemas.models import ExtractedNeed, VerifiedNeed

class VerificationAgent:
    def __init__(self, similarity_threshold: float = 0.85, confidence_threshold: float = 0.6):
        # We lazy-load the model to avoid huge startup times in tests
        self.model = None 
        self.similarity_threshold = similarity_threshold
        self.confidence_threshold = confidence_threshold

    def _get_model(self):
        if self.model is None:
            try:
                from sentence_transformers import SentenceTransformer
                self.model = SentenceTransformer('all-MiniLM-L6-v2')
            except Exception as e:
                # Fallback if not installed or network fails
                print(f"Warning: SentenceTransformer failed to load ({e}). Using difflib fallback.")
                import difflib
                class DummyModel:
                    def encode(self, texts):
                        # We will handle string comparison directly in compute_similarity for DummyModel
                        return texts
                self.model = DummyModel()
        return self.model

    def _compute_similarity(self, vec1, vec2) -> float:
        if isinstance(vec1, str) and isinstance(vec2, str):
            import difflib
            return difflib.SequenceMatcher(None, vec1, vec2).ratio()
            
        from numpy.linalg import norm
        if norm(vec1) == 0 or norm(vec2) == 0:
            return 0.0
        return np.dot(vec1, vec2) / (norm(vec1) * norm(vec2))

    def process(self, extracted: ExtractedNeed, existing_needs: List[VerifiedNeed]) -> VerifiedNeed:
        # 1. Base human review check
        requires_review = False
        if extracted.extraction_confidence < self.confidence_threshold:
            requires_review = True

        # 2. Deduplication check
        duplicate_of = None
        source_report_ids = [extracted.report_id]
        
        # Only attempt dedup if there are existing needs of the same type
        candidates = [n for n in existing_needs if n.need_type == extracted.need_type]
        
        if candidates:
            model = self._get_model()
            
            # Embed the new need
            text_new = f"{extracted.location_text} {extracted.need_type.value}"
            vec_new = model.encode([text_new])[0]
            
            # Embed the candidates
            texts_existing = [f"{c.location_text} {c.need_type.value}" for c in candidates]
            vecs_existing = model.encode(texts_existing)
            
            # Find matches above threshold
            matches = []
            for i, vec_existing in enumerate(vecs_existing):
                sim = self._compute_similarity(vec_new, vec_existing)
                if sim >= self.similarity_threshold:
                    matches.append((candidates[i], sim))
            
            if len(matches) == 1:
                match, sim = matches[0]
                duplicate_of = match.need_id
                source_report_ids = match.source_report_ids + [extracted.report_id]
            elif len(matches) > 1:
                # Ambiguous! Which one does it belong to?
                requires_review = True
                
        return VerifiedNeed(
            need_id=f"need-{extracted.report_id}", # Temporary ID, usually generated by DB
            source_report_ids=source_report_ids,
            location_text=extracted.location_text,
            coordinates=extracted.coordinates,
            need_type=extracted.need_type,
            quantity_estimate=extracted.quantity_estimate or 0,
            urgency=extracted.stated_urgency,
            verification_confidence=extracted.extraction_confidence,
            requires_human_review=requires_review,
            duplicate_of=duplicate_of
        )
