
from typing import List, Tuple, Optional
from backend.schemas.models import ExtractedNeed, VerifiedNeed

class VerificationAgent:
    def __init__(self, similarity_threshold: float = 0.85, confidence_threshold: float = 0.6):
        # We lazy-load the model to avoid huge startup times in tests
        self.model = None 
        self.similarity_threshold = similarity_threshold
        self.confidence_threshold = confidence_threshold

    def _get_model(self):
        if self.model is None:
            try:
                from sentence_transformers import SentenceTransformer
                self.model = SentenceTransformer('all-MiniLM-L6-v2')
            except Exception as e:
                # Fallback if not installed or network fails
                print(f"Warning: SentenceTransformer failed to load ({e}). Using difflib fallback.")
                import difflib
                class DummyModel:
                    def encode(self, texts):
                        # We will handle string comparison directly in compute_similarity for DummyModel
                        return texts
                self.model = DummyModel()
        return self.model


    def _get_vdb(self):
        if not hasattr(self, "vdb") or self.vdb is None:
            from backend.db.vector_store import VectorStore
            self.vdb = VectorStore()
        return self.vdb

    def process(self, extracted: ExtractedNeed, existing_needs: List[VerifiedNeed]) -> VerifiedNeed:
        # 1. Base human review check
        requires_review = False
        if extracted.extraction_confidence < self.confidence_threshold:
            requires_review = True

        # 2. Deduplication check
        duplicate_of = None
        source_report_ids = [extracted.report_id]
        
        model = self._get_model()
        vdb = self._get_vdb()
        
        # We search Qdrant instead of O(N) looping
        text_new = f"{extracted.location_text} {extracted.need_type.value}"
        vec_new = model.encode([text_new])[0]
        
        # search_similar(vector, need_type, limit, score_threshold)
        results = vdb.search_similar(
            vector=vec_new, 
            need_type=extracted.need_type.value,
            limit=2,
            score_threshold=self.similarity_threshold
        )
        print("DEBUG process results:", results)
        
        if len(results) == 1:
            match_id = results[0].payload.get("need_id")
            duplicate_of = match_id
            
            # Find the original need from existing_needs or we'd have to fetch it
            matched_need = next((n for n in existing_needs if n.need_id == match_id), None)
            if matched_need:
                source_report_ids = matched_need.source_report_ids + [extracted.report_id]
        elif len(results) > 1:
            requires_review = True
                
        new_need = VerifiedNeed(
            need_id=f"need-{extracted.report_id}", # Temporary ID, usually generated by DB
            source_report_ids=source_report_ids,
            location_text=extracted.location_text,
            coordinates=extracted.coordinates,
            need_type=extracted.need_type,
            quantity_estimate=extracted.quantity_estimate or 0,
            urgency=extracted.stated_urgency,
            verification_confidence=extracted.extraction_confidence,
            requires_human_review=requires_review,
            duplicate_of=duplicate_of
        )
        
        # If the need is successfully verified and not a duplicate, store in vector DB
        if not requires_review and not duplicate_of:
            self._get_vdb().upsert_need(new_need, vec_new)
            
        return new_need
